# Planning unit reconciliation {#sec-reconcile}

## Description

This module can be used to develop rules to resolve conflicting perspectives on land allocation. This module allows modification to the planning unit attribute table and dissolve planning unit per unique ID. Planning unit reconciliation is a process to resolve overlapping permits by referring to function reference maps. Reconciliation is done by analyzing how well the permit data matches the reference data.

## Usage

### Workflow

### Step-by step instructions

### Tips

## Data Requirements

### Input Data and Parameters

### Example Datasets

### Data Acquistion

## Outputs

### Output Files

### Report Interpretation

## Theoretical Background

### Model Description

The PUR module helps identify the location and extent of various overlapping area designations. These results can then be used as a basis for more open and directed discussions in the process of updating planning units.

### Key Assumptions

### Limitations

## References

\[ \@article{dewi2015negotiation, title={Negotiation support tools to enhance multifunctioning landscapes}, author={Dewi, Sonya and Ekadinata, Andree and Indiarto, Dony and Nugraha, Alfa and van Noordwijk, Meine}, book={ Climate-Smart Landscapes: Multifunctionality in Practice }, pages={444}, year={2015}, publisher={ World Agroforestry Centre (ICRAF)} }\]
