on:
  push:
    branches: 
      - main

name: render

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
    
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
          
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
          use-public-rspm: true
      - run: R -q -e 'install.packages(c("knitr", "rmarkdown", "ggplot2"))'   
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
            extra-packages: any::rcmdcheck
            needs: check
      
      - name: Render book
        run: quarto render
        
      - name: Render and Publish
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}